### ISSUE TITLE
Typing keybind letter is not possible

### ISSUE THREAD

**Issue by AlexanderRitter02** [AMereBagatelle/MCG#3]
### Disclaimer:
I have a pull request ready (as I needed that myself), but I'll create this issue first, because:
- My fix would require Fabric api, and you deliberately removed it in [this commit](https://github.com/AMereBagatelle/MCG/commit/1446853825524d6575a6fa47d8619d215a400667)

Please tell me if I should create it.

## The bug
Typing the keybind letter (default: Z) is **not possible** in text boxes (chat), in the anvil and in other GUIs.
It always opens the coordinate screen instead of typing the letter.
The issue is that the keybind Mixin implementation makes the key work regardless of circumstances, even if it should not.

**Comment by AMereBagatelle** [comment]
Please use the latest build, I have fixed this.

**Comment by AlexanderRitter02** [comment]
@AMereBagatelle Sorry, but neither the 1.16.x or the master branch build fixes this, just compiled from latest commits again.
You may have fixed it only locally? No idea, but I can say for sure it is not fixed here.

**Comment by AMereBagatelle** [comment]
Yes, sorry.  I have been forgetting to push all my commits for a while, should be fixed.
